import type { EmojiType } from "../components/icons/emojis/EmojiIcon";

export const EMOJIS_LIST: EmojiType[] = [
  "winking_face",
  "ace_with_bags_under_eyes",
  "beaming_face_with_smiling_eyes",
  "clapping_hands",
  "face_with_tears_of_joy",
  "grinning_face",
  "grinning_face_with_big_eyes",
  "grinning_face_with_smiling_eyes",
  "grinning_face_with_sweat",
  "grinning_squinting_face",
  "hand_with_fingers_splayed",
  "handshake",
  "heart_hands",
  "index_pointing_at_the_viewer",
  "melting_face",
  "ok_hand",
  "pinched_fingers",
  "pinching_hand",
  "raised_back_of_hand",
  "rolling_on_the_floor_laughing",
  "slightly_smiling_face",
  "smiling_face_with_halo",
  "smiling_face_with_heart_eyes",
  "smiling_face_with_hearts",
  "smiling_face_with_smiling_eyes",
  "star_struck",
  "thumbs_down",
  "thumbs_up",
  "upside_down_face",
  "victory_hand",
  "vulcan_salute",
  "waving_hand",
];
