export const LANGUAGES = [
  { code: "ar", englishName: "Arabic", nativeName: "العربية" },
  { code: "bn", englishName: "Bengali", nativeName: "বাংলা" },
  { code: "zh", englishName: "Chinese", nativeName: "中文" },
  { code: "nl", englishName: "Dutch", nativeName: "Nederlands" },
  { code: "en", englishName: "English", nativeName: "English" },
  { code: "fr", englishName: "French", nativeName: "Français" },
  { code: "de", englishName: "German", nativeName: "Deutsch" },
  { code: "el", englishName: "Greek", nativeName: "Ελληνικά" },
  { code: "he", englishName: "Hebrew", nativeName: "עברית" },
  { code: "hi", englishName: "Hindi", nativeName: "हिन्दी" },
  { code: "id", englishName: "Indonesian", nativeName: "Bahasa Indonesia" },
  { code: "it", englishName: "Italian", nativeName: "Italiano" },
  { code: "ja", englishName: "Japanese", nativeName: "日本語" },
  { code: "ko", englishName: "Korean", nativeName: "한국어" },
  { code: "ms", englishName: "Malay", nativeName: "Bahasa Melayu" },
  { code: "fa", englishName: "Persian", nativeName: "فارسی" },
  { code: "pl", englishName: "Polish", nativeName: "Polski" },
  { code: "pt", englishName: "Portuguese", nativeName: "Português" },
  { code: "pa", englishName: "Punjabi", nativeName: "ਪੰਜਾਬੀ" },
  { code: "ro", englishName: "Romanian", nativeName: "Română" },
  { code: "ru", englishName: "Russian", nativeName: "Русский" },
  { code: "es", englishName: "Spanish", nativeName: "Español" },
  { code: "sw", englishName: "Swahili", nativeName: "Kiswahili" },
  { code: "ta", englishName: "Tamil", nativeName: "தமிழ்" },
  { code: "te", englishName: "Telugu", nativeName: "తెలుగు" },
  { code: "th", englishName: "Thai", nativeName: "ไทย" },
  { code: "tr", englishName: "Turkish", nativeName: "Türkçe" },
  { code: "uk", englishName: "Ukrainian", nativeName: "Українська" },
  { code: "ur", englishName: "Urdu", nativeName: "اردو" },
  { code: "vi", englishName: "Vietnamese", nativeName: "Tiếng Việt" },
];

export const LANGUAGES_CODE_MAP = {
  ar: { code: "ar", englishName: "Arabic", nativeName: "العربية" },
  bn: { code: "bn", englishName: "Bengali", nativeName: "বাংলা" },
  zh: { code: "zh", englishName: "Chinese", nativeName: "中文" },
  nl: { code: "nl", englishName: "Dutch", nativeName: "Nederlands" },
  en: { code: "en", englishName: "English", nativeName: "English" },
  fr: { code: "fr", englishName: "French", nativeName: "Français" },
  de: { code: "de", englishName: "German", nativeName: "Deutsch" },
  el: { code: "el", englishName: "Greek", nativeName: "Ελληνικά" },
  he: { code: "he", englishName: "Hebrew", nativeName: "עברית" },
  hi: { code: "hi", englishName: "Hindi", nativeName: "हिन्दी" },
  id: { code: "id", englishName: "Indonesian", nativeName: "Bahasa Indonesia" },
  it: { code: "it", englishName: "Italian", nativeName: "Italiano" },
  ja: { code: "ja", englishName: "Japanese", nativeName: "日本語" },
  ko: { code: "ko", englishName: "Korean", nativeName: "한국어" },
  ms: { code: "ms", englishName: "Malay", nativeName: "Bahasa Melayu" },
  fa: { code: "fa", englishName: "Persian", nativeName: "فارسی" },
  pl: { code: "pl", englishName: "Polish", nativeName: "Polski" },
  pt: { code: "pt", englishName: "Portuguese", nativeName: "Português" },
  pa: { code: "pa", englishName: "Punjabi", nativeName: "ਪੰਜਾਬੀ" },
  ro: { code: "ro", englishName: "Romanian", nativeName: "Română" },
  ru: { code: "ru", englishName: "Russian", nativeName: "Русский" },
  es: { code: "es", englishName: "Spanish", nativeName: "Español" },
  sw: { code: "sw", englishName: "Swahili", nativeName: "Kiswahili" },
  ta: { code: "ta", englishName: "Tamil", nativeName: "தமிழ்" },
  te: { code: "te", englishName: "Telugu", nativeName: "తెలుగు" },
  th: { code: "th", englishName: "Thai", nativeName: "ไทย" },
  tr: { code: "tr", englishName: "Turkish", nativeName: "Türkçe" },
  uk: { code: "uk", englishName: "Ukrainian", nativeName: "Українська" },
  ur: { code: "ur", englishName: "Urdu", nativeName: "اردو" },
  vi: { code: "vi", englishName: "Vietnamese", nativeName: "Tiếng Việt" },
};
